mirror:
    image:
      name: alpine/git:latest
      entrypoint: ["/bin/sh"]
    script:
        - echo test 123
        - whereis git
        - whereis bash
        - git config --global push.default simple
        - git checkout ${CI_COMMIT_REF_NAME}
        - git push -q https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git

