mirror:
    image
        - name: "alpine/git:latest"
    script:
        - config --global push.default simple
        - checkout ${CI_COMMIT_REF_NAME}
        - push -q https://${GITHUB_USERNAME}:${GITHUB_TOKEN}@github.com/${GITHUB_REPO}.git

